### PR TITLE
Fix deletion of duplicate rpaths

### LINKED ISSUE #356: rpath deletion fails with duplicate rpaths
`pdnsrec` in Homebrew/core ships a binary with duplicate rpaths:
```
❯ otool -l pdns_recursor | rg -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 40
         path /usr/local/opt/boost/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 40
         path /usr/local/opt/boost/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 40
         path /usr/local/opt/boost/lib (offset 12)
```
Trying to delete this rpath fails with the following error:
```
[5] brew(main)> MachO::Tools.delete_rpath("pdns_recursor", "/usr/local/opt/boost/lib")
MachO::LoadCommandError: Unrecognized Mach-O load command: 0x00
from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-macho-2.5.0/lib/macho/macho_file.rb:530:in `block in populate_load_commands'
```
This is causing a bottling failure in Homebrew/core at https://github.com/Homebrew/homebrew-core/pull/77263.

### PR DESCRIPTION
**Pull request by carlocab**
Deferring field population to the end seems to break rpath deletion of
duplicated rpaths.

Closes #356.

-----

This might not be the ideal solution, but I think duplicated rpaths happen rarely enough for the performance hit to not be that bad.

Also, getting this into Homebrew/brew would unblock https://github.com/Homebrew/homebrew-core/pull/77263.

### CODE REVIEW

**Comment by carlocab** [comment]
I've added a test for the deletion of duplicate rpaths. To do so, I've checked in a binary `libdupe.dylib` into your test fixtures and amended the rpath deletion test to also delete the duplicated `/usr/lib` rpath.

I probably could've amended your `Makefile` to also generate duplicate rpaths in one of your existing test fixtures, but I was worried about breaking your existing tests.

**Comment by woodruffw** [comment]
Thanks for the fix! It's strange that deferring the population breaks deletion of duplicates, so that's something I should take a closer look at. This LGTM and I agree that the performance hit probably isn't too severe, so I'll merge now.

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
Cut with 2.5.1, thanks again!

**Comment by carlocab** [comment]
> Thanks for the fix! 

No problem! Thanks for your work on `ruby-macho`. I wish I had a better fix for you, but a lot of this stuff is way over my head at the moment.

> It's strange that deferring the population breaks deletion of duplicates, so that's something I should take a closer look at.

Yup, I agree.

> Cut with 2.5.1, thanks again!

Can we get that into Homebrew/brew?

**Comment by woodruffw** [comment]
> Can we get that into Homebrew/brew?

Yeah; it _should_ be as simple as `brew vendor-gems`; I think there's a `vendor-gems` workflow that can be used to run that update directly on the CI. I might not have permissions to do that anymore, though 🙂

**Comment by carlocab** [comment]
Oh, yes, I was vaguely aware of that. Just never used `vendor-gems` before. Ruby is still mostly voodoo to me 😄

**Pull request merged**
