### PR TITLE
Ignore duplicate rpaths in `#change_rpath`

### LINKED ISSUE #436: `change_rpath` differs in behaviour from `install_name_tool` when handling duplicates
Suppose I compile a dylib with a duplicate `RPATH`:
```
❯ clang -xc /dev/null -shared -rpath dupe -rpath dupe -o libdupes.dylib
❯ otool -l libdupes.dylib | rg -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 24
         path dupe (offset 12)
--
          cmd LC_RPATH
      cmdsize 24
         path dupe (offset 12)
```
(Admittedly, I don't know why one would do this, but `pdnsrec` still does.)

`change_rpath` handles changing one `RPATH` just fine, but chokes on the second:
```
❯ brew ruby -e 'MachO::Tools.change_rpath("libdupes.dylib", "dupe", "notdupe")'
❯ otool -l libdupes.dylib | rg -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 24
         path notdupe (offset 12)
--
          cmd LC_RPATH
      cmdsize 24
         path dupe (offset 12)
❯ brew ruby -e 'MachO::Tools.change_rpath("libdupes.dylib", "dupe", "notdupe")'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-macho-3.0.0/lib/macho/macho_file.rb:388:in `change_rpath': notdupe already exists (MachO::RpathExistsError)
        from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-macho-3.0.0/lib/macho/tools.rb:60:in `change_rpath'
        from -e:1:in `<main>'
```
`install_name_tool` chugs along just fine, though:
```
❯ install_name_tool -rpath dupe notdupe libdupes.dylib
❯ otool -l libdupes.dylib | rg -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 24
         path notdupe (offset 12)
--
          cmd LC_RPATH
      cmdsize 24
         path notdupe (offset 12)
```
This is slightly related to changes we made in #362 and #366, and I think I realised this shortly after, but this slipped off my radar.

It might be that this is intentional and nothing needs changing here, but I just wanted to bring this up just in case you want `ruby-macho` to behave more look `install_name_tool` here.

### PR DESCRIPTION
**Pull request by carlocab**
This causes a deviation in behaviour from `install_name_tool`, which
will happily change an existing rpath to one that already exists.

Closes #436.

### CODE REVIEW

**Comment by carlocab** [comment]
Even the existing test that I've just deleted seems to differ from `install_name_tool`'s behaviour:

```
❯ otool -l libdupes.dylib | rg -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 24
         path dupe (offset 12)
❯ install_name_tool -rpath dupe dupe libdupes.dylib
❯ echo $?
0
```

**Comment by woodruffw** [comment]
Hmm, I wonder if `install_name_tool`'s behavior changed beneath us. It wouldn't be the first time...

**Comment by carlocab** [comment]
I was wondering that too! But I don't have access to an old Mac to check.

**Comment by woodruffw** [comment]
Neither do I anymore, unfortunately. I remember we did quite a bit of behavioral testing against `install_name_tool` during the initial development here, so it wouldn't surprise me if things have changed. But we'll continue our policy of roughly following those changes 🙂

**Comment by carlocab** [comment]
Have you had the chance to think about how you want to handle this, @woodruffw?

**Comment by woodruffw** [comment]
Sorry for the delay!

And yeah: I think I agree that this change is for the best.

**Review by woodruffw — APPROVED** [review]

**Comment by carlocab** [comment]
No apologies necessary, and thanks!

**Pull request merged**
