### PR TITLE
workflows: pin setup-ruby action

### PR DESCRIPTION
**Pull request by Moisan**
Pin the version of the `setup-ruby` action to full length commit SHA as described in the [security hardening for GitHub Actions guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks @Moisan! Some failing CI here but may be able to remove that job.

**Review by woodruffw — APPROVED** [review]
(Failed job looks like a flake, re-running.)

**Comment by woodruffw** [comment]
Great, now everything is flaking on CodeCov 🙃

**Comment by woodruffw** [comment]
I guess we need a CodeCov token now. Fixing in another PR.

**Comment by woodruffw** [comment]
Fixed the CI failure with #597. although this is now broken because third-party (fork) PRs don't get access to `secrets.CODECOV_TOKEN`. I'm tempted to just remove the CodeCov integration altogether and replace it with a small workflow step that just spits out the coverage as a PR comment, since we don't treat coverage as a blocker anyways.

**Pull request closed without merging**
